Q1: Assign values to vector X and display them.

In [2]:
X <- c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20)
print(X)

 [1]  2  4  6  8 10 12 14 16 18 20


Q2: Assign the length of vector and determine its length.

In [3]:
length_X <- length(X)
print(length_X)

[1] 10


Q3: Access the 4th element, then 2nd and 10th elements.

In [4]:
print(X[4])
print(X[c(2, 10)])

[1] 8
[1]  4 20


Q4: Place X in Y, add 5 and 7 to it, then display Y.

In [5]:
Y <- c(X, 5, 7)
print(Y)

 [1]  2  4  6  8 10 12 14 16 18 20  5  7


Q5: Print Y except elements 11 and 12.

In [6]:
print(Y[-c(11, 12)])

 [1]  2  4  6  8 10 12 14 16 18 20


Q6: Print the first three values of Y.

In [7]:
print(Y[1:3])

[1] 2 4 6


Q7: Replace the first value of Y with 12.

In [8]:
Y[1] <- 12
print(Y)

 [1] 12  4  6  8 10 12 14 16 18 20  5  7


Q8: Replace the third value of Y with its square.

In [9]:
Y[3] <- Y[3]^2
print(Y)

 [1] 12  4 36  8 10 12 14 16 18 20  5  7


Q9: Replace 7th, 8th, and 9th values with 9, 8, and 7.

In [10]:
Y[7:9] <- c(9, 8, 7)
print(Y)

 [1] 12  4 36  8 10 12  9  8  7 20  5  7


Q10: Replace values > 8 in Y with 4.

In [11]:
Y[Y > 8] <- 4
print(Y)

 [1] 4 4 4 8 4 4 4 8 7 4 5 7


Q11: Sum, mean, median, sd, sqrt of Y.

In [12]:
sum_Y <- sum(Y)
mean_Y <- mean(Y)
median_Y <- median(Y)
sd_Y <- sd(Y)
sqrt_Y <- sqrt(Y)

print(sum_Y)
print(mean_Y)
print(median_Y)
print(sd_Y)
print(sqrt_Y)

[1] 63
[1] 5.25
[1] 4
[1] 1.712255
 [1] 2.000000 2.000000 2.000000 2.828427 2.000000 2.000000 2.000000 2.828427
 [9] 2.645751 2.000000 2.236068 2.645751


Q12: Create vector Z with rep(1:6, each=2) and display it.

In [13]:
Z <- rep(1:6, each=2)
print(Z)

 [1] 1 1 2 2 3 3 4 4 5 5 6 6


Q13: Add Y and Z, place result in W.

In [14]:
W <- Y + Z
print(W)

 [1]  5  5  6 10  7  7  8 12 12  9 11 13


Q14: Create S using seq(1, 23, 2).

In [15]:
S <- seq(1, 23, 2)
print(S)

 [1]  1  3  5  7  9 11 13 15 17 19 21 23


Q15: Perform S - W and show result.

In [16]:
result <- S - W
print(result)

 [1] -4 -2 -1 -3  2  4  5  3  5 10 10 10


Q16: Create matrix A from Y - Z - S. Is it square?

In [17]:
A <- Y - Z - S
matrix_A <- matrix(A, nrow=3)
print(matrix_A)
print(is.matrix(matrix_A) && nrow(matrix_A) == ncol(matrix_A))

     [,1] [,2] [,3] [,4]
[1,]    2   -1  -13  -20
[2,]    0   -8  -11  -22
[3,]   -3  -10  -15  -22
[1] FALSE


Q17: Square matrix from first 9 elements of X, 3x3. Show elements.

In [18]:
matrix_X <- matrix(X[1:9], nrow=3, byrow=TRUE)
print(matrix_X)

     [,1] [,2] [,3]
[1,]    2    4    6
[2,]    8   10   12
[3,]   14   16   18


Q18: Find determinant of matrix_X.

In [19]:
det_value <- det(matrix_X)
print(det_value)

[1] 0


Q19: Find transpose of matrix_X.

In [20]:
transpose_X <- t(matrix_X)
print(transpose_X)

     [,1] [,2] [,3]
[1,]    2    8   14
[2,]    4   10   16
[3,]    6   12   18


Q20: Find inverse of matrix_X.

In [21]:
inverse_X <- solve(matrix_X)
print(inverse_X)

ERROR: Error in solve.default(matrix_X): Lapack routine dgesv: system is exactly singular: U[3,3] = 0
